### ISSUE TITLE
[QUESTION] Chainway UHF

### ISSUE THREAD

**Issue by marianoarga** [amorenew/alps_uhf_flutter#1]
Hello, are you able to make a plugin for Chaiway C72 UHF RFID reader?
https://www.chainway.net/Support/Info/10

Thank you.

**Comment by amreniouinnovent** [comment]
@marianoarga This plugin is not universal support for UHF
fore each SDK it requires 2 to 3 full working days to make it perfect
As I see this link is your SDK http://203.86.28.33:15629/Files/Sdk/public/demo-uhf_as.rar

The steps I used to convert the Native SDK to Plugin:

1-Make a helper class to separate the SDK logic into simple and clean functions
like my UHFHelper

2-Map the helper to functions in the java plugin 

3-Listeners I used channels and RXJava for publishing to the channel.

**Comment by progaze** [comment]
I also asking for C72 plugin, can you make it available like this one?

**Comment by amreniouinnovent** [comment]
@progaze I made the current plugin in the daily job and I share it on Github
You could use it as a guideline to convert any similar SDK
It would take me 16 hours to convert C72 but I will not use it at all as it is not related to my job
